version: '3'
services:
  bot:
    build: .
    command: npm run start:dev
    depends_on:
      - db
    environment:
      - BOT_TOKEN=493149712:AAFNoXKSB8w4xaRyNmGCyRWiCUTTaOyBC-U
      - WEBHOOK_URL=
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/code